name: Run back end tests

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build and test Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Change directory to Java project root
        run: cd back

      - name: Build and test Java project
        run: mvn -B clean verify
        working-directory: back

      - name: Upload Jacoco code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/index.html
