name: SonarCloud Analysis

on:
  push:
    branches:
      - main
    paths:
      - 'back/**' # Path to backend code
      - 'front/**' # Path to frontend code
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
    paths:
      - 'back/**'
      - 'front/**'

jobs:
  sonarcloud-backend:
    name: SonarCloud Backend Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v2
        with:
          path: 'back'
      - name: Set up JDK 17 for backend
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Cache SonarCloud packages for backend
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Cache Maven packages for backend
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('back/pom.xml') }}
      - name: Build and analyze backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=quevala_bobapp_backend

  sonarcloud-frontend:
    name: SonarCloud Frontend Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v2
        with:
          path: 'front'
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
        working-directory: front
      - name: Cache SonarCloud packages for frontend
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - name: Build frontend
        run: npm run build
        working-directory: front
      - name: SonarCloud Scan for frontend
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}