name: Push images to Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Change directory to Java project root
        run: cd back

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push backend Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:latest

      - name: Change directory to frontend project root
        run: cd front

      - name: Set up Docker Buildx for frontend
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:latest