name: On push - Run all Java and Angular tests

on: [ push ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK 11 for Java tests
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Change directory to Java project root
      - name: Change directory to Java project root
        run: cd back

      # Build and test Java project with Maven
      - name: Build and test Java project
        run: mvn -B clean verify
        working-directory: back

      # Upload Jacoco code coverage report
      - name: Upload Jacoco code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: back/target/site/jacoco/index.html

      # Change directory to Angular project root
      - name: Change directory to Angular project root
        run: cd ../front

      # Install Angular dependencies
      - name: Install Angular dependencies
        run: npm install

      # Run Angular tests
      - name: Run Angular tests
        run: npm test

      # Archive Angular test coverage report
      - name: Archive Angular test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: angular-coverage-report
          path: front/coverage
